# Generated by Django 5.2.4 on 2025-07-10 23:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_text', models.CharField(max_length=191)),
                ('sub_display_text', models.CharField(max_length=191, null=True)),
                ('content_info', models.TextField(null=True)),
                ('relative_text', models.TextField(null=True)),
                ('is_installed', models.BooleanField(default=False)),
                ('version', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
